services:

  MineSweeper.API.Game:
    image: mag
    build:
      dockerfile: Docker/Production/MineSweeper.API.Game.Dockerfile
      context: .
    ports:
      - "8081:80"
    networks:
      - internal

  MineSweeper.Blazor.Server:
    image: mbs
    build: 
      dockerfile: Docker/Production/MineSweeper.Blazor.Server.Dockerfile
      context: .
    ports:
      - "8080:80"
    environment:
      - APIURL=http://MineSweeper.API.Game:80/Game/
    depends_on:
      - MineSweeper.API.Game
    networks:
      - external
      - internal

  MineSweeper.Score.API:
    image: msa
    build: 
      dockerfile: Docker/Production/MineSweeper.API.Score.Dockerfile
      context: .
    ports:
      - "8084:80"
    environment:
      - DB_HOST=MineSweeper.Score.Database
      - DB_USER=sa
      - DB_PASS=My_password_1
    depends_on:
      - MineSweeper.Score.Database
    networks:
      - internal

  MineSweeper.Score.Database:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=My_password_1
    networks:
      - internal

networks:
  internal:
    driver: bridge
    internal: true

  external:
    driver: bridge