services:

  MineSweeper.API.Game:
    image: mgs
    build:
      dockerfile: Docker/Production/MineSweeper.API.Game.Dockerfile
      context: .
    ports:
      - "8081:80"

  MineSweeper.Score.API:
    image: mbs
    build: 
      dockerfile: Docker/Production/MineSweeper.API.Score.Dockerfile
      context: .
    ports:
      - "8084:80"
    environment:
      - DB_HOST=value
      - DB_USER=value
      - DB_PASS=value
    depends_on:
      - MineSweeper.Score.Database

  MineSweeper.Blazor.Server:
    image: mbs
    build: 
      dockerfile: Docker/Production/MineSweeper.Blazor.Server.Dockerfile
      context: .
    ports:
      - "8080:80"
    environment:
      - APIURL=http://MineSweeper.Game.Server:80/Game/
    depends_on:
      - MineSweeper.Game.Server

  MineSweeper.Score.Database:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y

