name: CICD

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: "Print1"
          run: ls

        - name: "Restore"
          run: dotnet restore

        - name: "Build"
          run: dotnet build --no-restore

        - name: "Print2"
          run: ls

        - name: "Test"
          run: dotnet test

