name: CICD

on:
  push:
  workflow_dispatch:

jobs:
  CICD:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        
        - name: "Restore"
          run: dotnet restore

        - name: "Build"
          run: dotnet build --no-restore

        - name: "Test"
          run: dotnet test

