name: CICD

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build"
        run: |
          dotnet restore
          dotnet build
      - name: "Test"
        run: |
          dotnet test

